# plex and oversserr
# Add sonarr and radarr
version: '3'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
     - ./plex/config:/config
     - ./plex/transcode:/transcode
     - ./data/media:/data/media
    environment:
     - PLEX_CLAIM="claim-xx_EJFuG4S8iRGZrxKkA"
    ports:
      - 32400:32400
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - LOG_LEVEL=debug
      - PORT=5055 #optional
    volumes:
      - ./overseerr/config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./sonarr/config:/config
      - ./data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./radarr/config:/config
      - ./data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
